FROM centos:8
MAINTAINER chuflegets <chuflegets@gmail.com>
RUN yum -y upgrade && yum -y groupinstall "Development Tools" && yum -y install expect zlib-devel libffi-devel bzip2-devel openssl-devel sqlite-devel readline-devel
