#!/usr/bin/env python
import re
import subprocess



def load_whishlist(filename):
    with open(filename, 'r') as whishlist:
        return [line.strip() for line in whishlist]


def find_executables(whishlist):
    return {executable: subprocess.check_output(['which', executable]).strip() for executable in whishlist}


def clean(libraries):
    for dependency in libraries:
        if len(dependency) < 2 or dependency[1] == '':
                libraries.remove(dependency)
    return libraries


def gather_libraries(whishlist):
    dependencies = set()
    for executable, location in whishlist.items():
        try:
            libraries = clean([parse_ldd_entry(line) for line in subprocess.check_output(['ldd', location]).strip().split('\t')])
            dependencies = dependencies | set(tuple(item) for item in libraries)
        except subprocess.CalledProcessError:
            continue
    return dependencies


def parse_ldd_entry(line):
    tokens = re.split(r'\s*=>\s*', line.strip())
    return [re.sub(r'\(0[xX][\da-f]+\)', '', token).strip() for token in tokens]


def create_rootfs(jail_folder, whishlist, dependencies):
    # Make directories
    subprocess.check_output(['mkdir', jail_folder])
    for folder in ('bin', 'lib64', 'etc', 'dev', 'proc', 'sys', 'root'):
        subprocess.check_output(['mkdir', jail_folder + '/' + folder])

    # Copy executable binaries to their path in jail
    for executable, location in whishlist.items():
        subprocess.check_output(['cp', location, jail_folder + '/bin'])

    # Copy system objects to their path in jail
    for dependency in dependencies:
        subprocess.check_output(['cp', dependency[1], jail_folder + '/lib64'])
    
    # Link dependencies to executables
    subprocess.check_output(['cp', '/lib64/ld-linux-x86-64.so.2', jail_folder + '/lib64'])
    # Enable DNS resolution
    subprocess.check_output(['cp', '/etc/resolv.conf', jail_folder + '/etc'])


def main():
    whishlist = load_whishlist('whishlist')
    whishlist = find_executables(whishlist)
    dependencies = gather_libraries(whishlist)
    create_rootfs('chroot_jail', whishlist, dependencies)


if __name__ == '__main__':
    main()

