#!/bin/bash
num_processors=$((2*$(nproc --all)))
cd /tmp/postgresql-12.0
./configure --with-pam --with-ldap --with-openssl --with-gnu-ld
make -j$num_processors
make install
useradd --no-create-home postgres
cd $OLDPWD && rm -rf /tmp/postgresql-12.0
